# This is a basic workflow that is manually triggered

name: Make javascript files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  deployment:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: omajinai
      uses: actions/checkout@v1
    # Runs a single command using the runners shell
    - name: install typescript and do transcompile.
      run: npm install typescript; npx tsc
